export type Project = {
  slug: string;
  category: string;
  name: string;
  description: string;
  technologies: string[];
  image: string;
  region: string;
  /**
   * Live product, when the client publishes one. Opened in a new tab, so these are
   * absolute `https` URLs and never routed through `next/link`.
   */
  url?: string;
  /**
   * Short outcome line, the one number a buyer wants. Kept separate from
   * `description` so cards and case studies read differently.
   */
  result: string;
  /** Which service this work was delivered under, used to link the card onward. */
  service: "ecommerce" | "crm" | "erp" | "erpnext" | "pos" | "custom-software";
};

/**
 * Selected work.
 *
 * These are real client projects. `result` states the outcome the client saw, in the
 * client's terms.
 *
 * `image` is either final artwork or a generated placeholder, and never a missing
 * file. Final artwork is `.webp`; anything still on `.svg` has no artwork yet and is
 * regenerated by `scripts/generate-project-placeholders.mjs`. Keep both paths served
 * through `next/image`, which is what resizes these for delivery.
 */
export const projects: Project[] = [
  {
    slug: "captain-chef",
    category: "Ecommerce",
    name: "Captain Chef",
    description:
      "A food ordering platform built for volume at peak hours: menu, payments, kitchen display and delivery tracking on one order pipeline.",
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Payment APIs"],
    image: "/images/projects/captain-chef.webp",
    url: "https://captainchef.net/",
    region: "Saudi Arabia",
    result: "Order pipeline handles peak volume without manual intervention",
    service: "ecommerce",
  },
  {
    slug: "smle-guide",
    category: "Custom Software",
    name: "SMLE Guide",
    description:
      "A study companion for medical licensing candidates: question banks, timed practice, performance analytics and revision scheduling.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL"],
    image: "/images/projects/smle-guide.webp",
    url: "https://www.smleguide.com/",
    region: "Saudi Arabia",
    result: "Practice analytics turned weak topics into a tracked study plan",
    service: "custom-software",
  },
  {
    slug: "baba-foods",
    category: "ERP",
    name: "Baba Foods",
    description:
      "An ERP rollout covering purchasing, inventory, production and distribution, with historic data migrated and staff trained on the new flow.",
    technologies: ["ERPNext", "Frappe", "MySQL"],
    image: "/images/projects/baba-foods.webp",
    region: "Saudi Arabia",
    result: "One inventory truth across purchasing, stock and dispatch",
    service: "erpnext",
  },
  {
    slug: "umrah-online",
    category: "Ecommerce",
    name: "Umrah Online",
    description:
      "An ecommerce and operations platform for Umrah travel: package booking, customer records, payment handling and partner reporting.",
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Cloud Deployment"],
    image: "/images/projects/umrah-online.webp",
    url: "https://play.google.com/store/apps/details?id=net.umrahonline.umrahonline&hl=en",
    region: "Saudi Arabia",
    result: "Bookings, payments and partner reporting in a single system",
    service: "ecommerce",
  },
  {
    slug: "drs-lounge",
    category: "POS",
    name: "Dr's Lounge",
    description:
      "A point of sale and client system for a beauty lounge: bookings, service history, staff scheduling and end of day reconciliation.",
    technologies: ["Volt", "SQLite", "Docker", "Printing Integration"],
    image: "/images/projects/drs-lounge.webp",
    url: "https://play.google.com/store/apps/details?id=pk.drslounge.app&hl=en",
    region: "Dubai, UAE",
    result: "Bookings, sales and staff hours reconciled daily",
    service: "pos",
  },
  {
    slug: "mellot",
    category: "Custom Software",
    name: "Mellot",
    description:
      "A customer relationship platform built around the way the team actually sells: pipeline, follow up scheduling and performance reporting.",
    technologies: ["Next.js", "Node.js", "PostgreSQL"],
    image: "/images/projects/mellot.svg",
    region: "Gulf Region",
    result: "Pipeline and follow ups visible to the whole sales team",
    service: "crm",
  },
  {
    slug: "salon-zc",
    category: "POS",
    name: "Salon ZC",
    description:
      "A salon management system combining point of sale, inventory, staff commissions and multi branch reporting.",
    technologies: ["Next.js", "PostgreSQL", "Cloud Deployment"],
    image: "/images/projects/salon-zc.svg",
    region: "Saudi Arabia",
    result: "Multi branch reporting from a single source of data",
    service: "pos",
  },
];
